package luzVerdeVerticles;

import java.util.Calendar;
import java.util.Random;

import io.netty.handler.codec.mqtt.MqttConnectReturnCode;
import io.netty.handler.codec.mqtt.MqttQoS;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.Json;
import io.vertx.mqtt.MqttClient;
import io.vertx.mqtt.MqttClientOptions;
import io.vertx.mqtt.impl.MqttClientImpl;
import luzVerdeTipos.ValorSensorContaminacion;

public class MqttClientVerticle extends AbstractVerticle{
	
	private String classInstanceId;
	
	public void start (Promise<Void> promise) {
		classInstanceId = this.hashCode() + "";
		MqttClientOptions mqttClientOptions = new MqttClientOptions();
		mqttClientOptions.setAutoKeepAlive(true);
		mqttClientOptions.setAutoGeneratedClientId(false);
		mqttClientOptions.setClientId(classInstanceId);
		mqttClientOptions.setConnectTimeout(10000);
		mqttClientOptions.setKeepAliveTimeSeconds(10);
		mqttClientOptions.setReconnectAttempts(10);
		mqttClientOptions.setReconnectInterval(5000);
		mqttClientOptions.setUsername("cruce1");
		mqttClientOptions.setPassword("zeus");
		MqttClient mqttClient = new MqttClientImpl(vertx, mqttClientOptions);
		
		mqttClient.publishHandler(messageReceivedHandler -> {
			System.out.println(messageReceivedHandler.payload().toString());
		});
		
		mqttClient.connect(1885,"localhost", handler -> {
			
			if(handler.result().code() == MqttConnectReturnCode.CONNECTION_ACCEPTED) {
				
				mqttClient.subscribe(MqttServerVerticle.TOPIC_LUZ, MqttQoS.AT_LEAST_ONCE.value(), handlerSubscribe -> {
					if(handlerSubscribe.succeeded()) {
						System.out.println(classInstanceId + " subscribed to " + MqttServerVerticle.TOPIC_LUZ + " topic");
						vertx.setPeriodic(8000, periodic -> {
							Random random = new Random();
							ValorSensorContaminacion sensorValue = new ValorSensorContaminacion(1, 1, 30 + random.nextInt(10), 5 + random.nextInt(5), Calendar.getInstance().getTimeInMillis());
							mqttClient.publish(MqttServerVerticle.TOPIC_LUZ, Buffer.buffer(Json.encodePrettily(sensorValue)) , MqttQoS.AT_LEAST_ONCE, false, true);
						});
					}else {
						System.out.println(classInstanceId + "NOT suscribed to" + MqttServerVerticle.TOPIC_LUZ);
					}
				});
			}else {
				System.out.println("Error: "+handler.result().code());
			}
		});
	}
}
